default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: suvichaar_development

test:
  <<: *default
  database: suvichaar_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  # Add this to satisfy Action Cable / Solid Cable
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
