default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: dhruv
  password: 3829
  pool: 5

development:
  <<: *default
  database: suvichaar_development

test:
  <<: *default
  database: suvichaar_test

production:
  <<: *default
  database: suvichaar_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
